### ISSUE TITLE
Settings option not responding

### ISSUE THREAD

**Issue by abdul-qudus** [CCninja86/UltimateWordFinder#30]
#### Project Information
* Repository:

* Project Name: 
* Publisher: 

#### Expected behavior
While operating on the app, making use of any option should correspond to any activity selected on clicked on. E.g when clicking on start game, game should start with immediate effect. 

#### Actual behavior
When app is been opened and trying to check the settings option, pop up should be activated which will include many more options to make games settings to your taste. But when clicking on the settings option no response is been detected.

#### How to reproduce
1. Open application.
2. At the top right corner, click on the menu option to display settings option.
3. Click on settings.
4. Bug is visible.

***
* Browser/App version: ultimate word finder 1.05.
* Operating system: Android Nougat 7.0
***
#### Recording Of The Bug
https://youtu.be/uMEG7VQ2Iwo

**Comment by CCninja86** [comment]
Hi. Thanks for the feedback. Although I haven't implemented any customisable settings yet, that should still link to the feedback section of the app for reporting bugs.  That section is still a WIP as my but reporting process has changed since I first developed it, but I'll get it working as soon as possible. I have a major update coming shortly with Material Design and a new game setup screen. I'm include the fix with that update.

**Comment by abdul-qudus** [comment]
Alright sir. Thanks for the reply. But using this settings option doesn't
tend to even display any result including the about option. The about
option is located when the game starts. I will be glad to see the updates
on the app. Thanks.

**Comment by CCninja86** [comment]
The options menu is now consistent throughout the app in the latest version of the material-ui-redesign branch.
